export default {
  orCircle: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    transform: 'translate(-50%, -50%)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    fontSize: '18px',
    fontWeight: 300,
    zIndex: 5,
    backgroundColor: '#424242',
    borderRadius: '50%',
    width: '60px',
    height: '60px',
    border: '1px solid #616161',
    boxShadow: '0px 0px 18px 3px rgba(0, 0, 0, 0.1)',
  },
};
