name: main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ '*' ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:

      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: ./scripts/prepare-ci.sh
        env:
          FIREBASE_AUTH_DOMAIN: stub-project.firebaseapp.com
          FIREBASE_DATABASE_URL: stub-project.firebaseio.com

      - run: npm ci
      - run: npm run build
      - run: npm test
